config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
  resources :works
end

app/models/api.rb
class Api < ApplicationRecord
  has_many :works
  has_many :locations, through: :works

  validates :category, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/json_request.rb
class JsonRequest < ApplicationRecord
  belongs_to :location
  belongs_to :user
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :works
  has_many :apis, through: :works

  validates :city, presence: true
  validates :country, presence: true
  validates :country_key, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token :rid
  has_and_belongs_to_many :works

end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :location
  belongs_to :api
  has_and_belongs_to_many :users

  validates :location_id, presence: true
  validates :api_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # cookies.delete :weather_api_setcs

  include ApplicationHelper

  private

  def current_user
    if !cookies[:weather_api_setcs]
      user = User.create
      cookies.signed[:weather_api_setcs] = user.rid
      user
    else
      user = User.find_by rid: cookies.signed[:weather_api_setcs]

      if user
        user
      else
        user = User.new
        user.rid = cookies.signed[:weather_api_setcs]
        user.save
        user
      end
    end
  end

  def get_location(country, country_key, city)
    location = Location.find_by country_key: country_key, city: city
    if location
      location
    else
      Location.create(city: city, country: country, country_key: country_key)
    end
  end

  def get_country(country_key)
    if country_key != 'EMPTY'
      IsoCountryCodes.find(country_key).name
    else
      nil
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @weather_show = weather_show
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  def create

    if form_region[:city].blank?
      @weather_show = weather_show
      @error = 'please enter city'
      return
    end

    country = get_country(form_region[:country_key])

    location = GetCountryAndCity.new(country, form_region[:country_key], form_region[:city]).call
    if !location
      @weather_show = weather_show
      @error = 'can\'t find location'
      return
    end

    country_key = location[:country_key]
    city = location[:city]
    country = location[:country]


    location = get_location(country, country_key, city)
    user = current_user

    weather = WeatherUpdate.new(location, user).call

    @error = ''
    @weather_show = weather_show

    respond_to do |format|
      format.js
    end

  end

  def destroy
    user = current_user
    location_id = params[:id].to_i

    if user
      user.works.where(location_id: location_id).each do |el|
        user.works.delete(el.id)
        #user.works.clear
      end
    end

    @weather_show = weather_show

    respond_to do |format|
      format.js { render template: "works/create" }
    end
  end

  def show

  end

  def new
    cookies.delete :weather_api_setcs
  end

  private
  def form_region
    params.require(:form_region).permit(:city, :country_key)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def weather_show
    user = current_user

    if user
      weathers = user.works
      if weathers.size > 0
        results = Hash.new {|h,k| h[k] = {} }


        weathers.each_with_index do |ob, index|
          if ob.api.json
            results[index][:json] = eval(ob.api.json)
          end

          results[index][:id] = ob.location_id
          # puts "#{ob.api.class}<---"

        end
      end
      return results
    end
    false
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Weather
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = yield

app/views/shared/_weather.html.haml
.weather_block
  - weather_show.each do |i|
    - if i.second[json_key]
      - i.second[json_key].each do |i1|
        - if i1.first!=:error
          - if i1.first==0
            .country
              = i1.second[:city]
              | #{i1.second[:country]}&nbsp;#{link_to 'Destroy', work_path(i.second[:id]), method: :delete, remote: true, data: { confirm: 'Are you sure?' }}
          %ul
            %li= i1.second[:date]
            %li= i1.second[:sky]
            %li
              min C° #{i1.second[:temp_min]}
            %li
              max C° #{i1.second[:temp_max]}

app/views/shared/_work.html.haml
- if @weather_show
  = render partial: "shared/weather", locals: { weather_show: @weather_show, json_key: :json }
  // = render partial: "shared/weather", locals: { weather_show: @weather_show, json_key: :json_wunderground }

app/views/users/index.html.haml
= form_for :form_region, url: {controller:"works", action: "create"}, html: {class: "user_form"}, remote: true do |f|
  .form-group
    %select{:name => "form_region[country_key]", :id => "custom_select"}
      %option{:value => "EMPTY"}
      - IsoCountryCodes.for_select.each do |i|
        %option{:value => i.second}= i.first
  .form-group
    = f.text_field :city, class: "form-control", placeholder: "city"
  .form-group
    = f.submit "select", class: "btn, btn-default"

#error

#result
  = render partial: "shared/work"

app/views/works/create.js.haml
// $("#result").html("<%#=j render partial: 'shared/work', locals: { json_1: @json_1, json_2: @json_2 } %>");
$("#result").html("#{j render partial: 'shared/work'}");

- if @error
    $("#error").html("#{ @error }")

app/views/works/new.html.erb
123

app/views/works/select_country.html.erb
<pre><%= JSON.pretty_generate(@city) %></pre>